name: Includes Jira issue

# Run on push to any branch
on: [pull_request]

jobs:
  commit-linting:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: '${{ github.event.pull_request.base.ref }}'

    - name: Branch or Commits includes a Jira issue
      run: |
        git checkout ${{ github.event.pull_request.head.ref }}
        bash ${GITHUB_WORKSPACE}/.github/scripts/commit-linting-loose.sh ${{ github.event.pull_request.head.ref }} ${{ github.event.pull_request.base.ref }}