name: Commit Checker

# Run on push to any branch
on: [pull_request]

jobs:
  commit-checker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: '${{ github.event.pull_request.base.ref }}'

    - name: Commit validation
      run: bash ${GITHUB_WORKSPACE}/scripts/commit-checker.sh ${{ github.event.pull_request.head.ref }} ${{ github.event.pull_request.base.ref }}
        